theme = "onedark"

[editor]
line-number = "relative"
auto-completion = true
auto-info = true

[editor.statusline]
left = ["mode"]
center=["file-name"]
right = ["diagnostics", "position-percentage"]
separator = "|"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
L = "goto_line_end"
H = "goto_line_start"
G = "goto_last_line"
