theme = "onedark"

[editor]
line-number = "relative"
auto-completion = true
auto-info = true
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode"]
center=["file-name"]
right = ["diagnostics", "position-percentage"]
separator = "|"

[editor.cursor-shape]
insert = "bar"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
G = "goto_last_line"
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
space.y = "@\"%p<space>Yd"
