# pip install -U 'python-lsp-server[all]'
# pip install python-lsp-ruff

[[language]]
name = "python"
language-server = { command = "pylsp"}

[language.config.pylsp.plugins]
ruff = {enabled = true, extendSelect = ["I"]}
